export const TestData = {
	rest_request_id: "e3ec62a5-250a-45f1-85d8-4e21c3565689",
	message: "Vehicle shared.",
	vehicle_share: {
		customer_message:
			"Here is the personalized presentation for the Wrangler you are looking at.  We hope this helps you in your buying process.\n\nShould you have any questions, please feel free to reach out!\n\n-\n",
		id: null,
		number_of_views: 0,
		customer_name: "John",
		customer_phone: null,
		customer_email: null,
		inventory_item: {
			city_liters_per_100_km: 12.379473684210527,
			highway_liters_per_100_km: 9.800416666666667,
			number_of_views: 0,
			last_viewed_at: null,
			id: 102285,
			inventory_id: "7b6cd0bd-a9a5-4d66-bf98-7927f053bda9",
			stock_number: "J20283",
			vin: "1C4HJXDN3NW134746",
			make: "Jeep",
			model: "Wrangler",
			year: 2022,
			condition: "New",
			selling_price: 32039,
			internet_price: 0,
			engine_description: "Intercooled Turbo Premium Unleaded I-4 2.0 L/122",
			highway_miles_per_gallon: 24,
			city_miles_per_gallon: 19,
			distance_units: "MI",
			exterior_color_description: "Silver Zynith Clearcoat",
			interior_color_description: "Black",
			description:
				"Buy with confidence knowing you have our $500 Best Price Guarantee: Simply put, no other dealer will beat our price on any of our in-stock units. Factory MSRP: $39,770<br><br>2022 Jeep Wrangler Unlimited Sport Silver Zynith Clearcoat 4WD 2.0L I4 DOHC",
			miles: 10,
			created_at: "2022-03-02T21:50:03.901Z",
			store_id: 1000,
			is_active: true,
			transmission_name: "Automatic",
			transmission_drive_type: "4WD",
			trim: "Unlimited Sport",
			date_added_to_inventory: "2022-03-02",
			stored_image_filename: null,
			is_commercial: false,
			inventory_item_photos: [
				{
					id: 83,
					url: "https://loopmein-dev.imgix.net/inventory/1d7a2c8c-ad3c-4044-93e2-3022702f3120.jpg"
				},
				{
					id: 825,
					url: "https://loopmein-dev.imgix.net/inventory/c32ea9aa-d92c-4d0c-8f12-43f5152ba836.jpg"
				},
				{
					id: 822,
					url: "https://loopmein-dev.imgix.net/inventory/5a9edc42-79c4-47fb-b01b-1597352fb77e.jpg"
				},
				{
					id: 852,
					url: "https://loopmein-dev.imgix.net/inventory/271a53c9-785b-4e7a-a1e6-2f2c27673ad7.jpg"
				},
				{
					id: 8255,
					url: "https://loopmein-dev.imgix.net/inventory/c32ea9aa-d92c-4d0c-8f12-43f5152ba836.jpg"
				},
				{
					id: 8422,
					url: "https://loopmein-dev.imgix.net/inventory/5a9edc42-79c4-47fb-b01b-1597352fb77e.jpg"
				},
				{
					id: 152,
					url: "https://loopmein-dev.imgix.net/inventory/271a53c9-785b-4e7a-a1e6-2f2c27673ad7.jpg"
				}
			],
			store: {
				id: 1000,
				organization_id: 1,
				is_active: true,
				hours: {
					days: [
						{
							day: 0,
							day_text: "Sunday",
							open: false,
							open_time: null,
							close_time: null
						},
						{
							day: 1,
							day_text: "Monday",
							open: true,
							open_time: "0802",
							close_time: "1800"
						},
						{
							day: 2,
							day_text: "Tuesday",
							open: true,
							open_time: "0830",
							close_time: "1800"
						},
						{
							day: 3,
							day_text: "Wednesday",
							open: true,
							open_time: "0830",
							close_time: "1800"
						},
						{
							day: 4,
							day_text: "Thursday",
							open: true,
							open_time: "0830",
							close_time: "1800"
						},
						{
							day: 5,
							day_text: "Friday",
							open: true,
							open_time: "0830",
							close_time: "1730"
						},
						{
							day: 6,
							day_text: "Saturday",
							open: true,
							open_time: "1000",
							close_time: "1900"
						}
					],
					timezone: "America/Denver",
					open_now: true,
					open_now_calc: true
				},
				paywall_setting: "1",
				store_photos: [
					{
						full_url: "https://loopmein-dev.imgix.net/store-photos/1000/668304fa-3e00-4b33-a6f8-f6d09a055cdc.jpg",
						id: 33,
						sort_order: 100,
						relative_url: "/store-photos/1000/668304fa-3e00-4b33-a6f8-f6d09a055cdc.jpg"
					},
					{
						full_url: "https://loopmein-dev.imgix.net/store-photos/1000/bfd5b011-80b3-418a-89b2-533a20152b62.png",
						id: 34,
						sort_order: 100,
						relative_url: "/store-photos/1000/bfd5b011-80b3-418a-89b2-533a20152b62.png"
					},
					{
						full_url: "https://loopmein-dev.imgix.net/store-photos/1000/ff18abf9-d3cf-45ac-b30b-65994e6c3a82.png",
						id: 35,
						sort_order: 100,
						relative_url: "/store-photos/1000/ff18abf9-d3cf-45ac-b30b-65994e6c3a82.png"
					},
					{
						full_url: "https://loopmein-dev.imgix.net/store-photos/1000/7f203074-1978-4645-a590-a1635c05cfdf.png",
						id: 36,
						sort_order: 100,
						relative_url: "/store-photos/1000/7f203074-1978-4645-a590-a1635c05cfdf.png"
					},
					{
						full_url: "https://loopmein-dev.imgix.net/store-photos/1000/d47dac23-9dbe-4b5d-af02-27184a528a1f.png",
						id: 37,
						sort_order: 100,
						relative_url: "/store-photos/1000/d47dac23-9dbe-4b5d-af02-27184a528a1f.png"
					}
				],
				name: "Loopmein Buick GMC",
				logo_url: "https://loopmein-dev.imgix.net/stores/f8c39fb2-e787-4f14-8a9e-e2ffeed08e5d.png",
				primary_photo_url: "https://loopmein-dev.imgix.net/store-photos/1000/d47dac23-9dbe-4b5d-af02-27184a528a1f.png",
				phone: null,
				address1: "quick test 2",
				address2: null,
				city: "Lafayette",
				state: "CA",
				zip: "47905",
				country_code: "US",
				testimonial: null,
				why_us: "Just because!",
				website_url: "https://amazon.com",
				sales_phone: "7654473191",
				sales_email: "dan+sales@jsoftllc.com"
			}
		},
		salesperson: {
			has_sms: true,
			bio_text: "A hip, a hip, a hibbie, to the hibbie, the hip hip hop and you don't stop, you rock. OH dang",
			photo_url: "https://loopmein-dev.imgix.net/users/e705cf85-6cd4-4e78-acc0-bceaee870ae8.jpg?w=200&facepad=2&faceindex=1&fit=facearea",
			sales_type_id: 2,
			name: "Juan Ocho Boraccho",
			phone: "8015551212",
			sms_phone: "8015552121",
			email: "borrachoninja@gmail.com",
			job_title_name: "Car Salesman",
			bio: "",
			photo_relative_url: null
		},
		background_image: "https://loopmein-dev.imgix.net/coverpages/stores/1000/197bbb2a-594b-4e77-b3e5-a580db5d710b.jpg",
		theme: 0,
		show_salesperson: true
	},
	vehicle_documents: [
		{
			id: 458,
			database_id: 458,
			relative_url: "/vehicle-documents/e3fc4724-289a-4f85-b82c-f926bd584761.jpg",
			vehicle_document_type_id: 88,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: 1000,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: "New",
			customer_can_view: true,
			name: null,
			external_url: null,
			is_active: true,
			document_type_name: "CPO Brochure",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/e3fc4724-289a-4f85-b82c-f926bd584761.jpg",
			is_external: false,
			display_name: "",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 402,
			database_id: 402,
			relative_url: "/vehicle-documents/3b47a850-6d77-4e4d-b07b-619bca0028f9.jpg",
			vehicle_document_type_id: 13,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: 1000,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: "Another image upload test",
			external_url: null,
			is_active: true,
			document_type_name: "Why Buy",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/3b47a850-6d77-4e4d-b07b-619bca0028f9.jpg",
			is_external: false,
			display_name: "Another image upload test",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 436,
			database_id: 436,
			relative_url: "/vehicle-documents/baebb752-ac90-40aa-acd7-85ffaa94f2e7.pdf",
			vehicle_document_type_id: 81,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: 1000,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: "Another test document",
			external_url: null,
			is_active: true,
			document_type_name: "Manual",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/baebb752-ac90-40aa-acd7-85ffaa94f2e7.pdf",
			is_external: false,
			display_name: "Another test document",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 429,
			database_id: 429,
			relative_url: "/vehicle-documents/22856f8f-e67f-477c-b2f7-0c87e5eddfca.png",
			vehicle_document_type_id: 81,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: 1000,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: "logo",
			external_url: null,
			is_active: true,
			document_type_name: "Other",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/22856f8f-e67f-477c-b2f7-0c87e5eddfca.png",
			is_external: false,
			display_name: "logo",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 380,
			database_id: 380,
			relative_url: "/vehicle-documents/0be95876-955b-4efc-b88b-211a3d954fee.png",
			vehicle_document_type_id: 81,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: null,
			organization_id: 1,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: "Image upload test",
			external_url: null,
			is_active: true,
			document_type_name: "Other",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/0be95876-955b-4efc-b88b-211a3d954fee.png",
			is_external: false,
			display_name: "Image upload test",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 376,
			database_id: 376,
			relative_url: "/vehicle-documents/391798c3-f259-492a-bc9b-9c05d4a85509.jpg",
			vehicle_document_type_id: 74,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: null,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: null,
			external_url: null,
			is_active: true,
			document_type_name: "Supplemental Manual",
			document_type_description: "YMM",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: false,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/391798c3-f259-492a-bc9b-9c05d4a85509.jpg",
			is_external: false,
			display_name: "",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 1402,
			database_id: 402,
			relative_url: "/vehicle-documents/3b47a850-6d77-4e4d-b07b-619bca0028f9.jpg",
			vehicle_document_type_id: 13,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: 1000,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: "Another image upload test",
			external_url: null,
			is_active: true,
			document_type_name: "Why Buy",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/3b47a850-6d77-4e4d-b07b-619bca0028f9.jpg",
			is_external: false,
			display_name: "Another image upload test",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 4436,
			database_id: 436,
			relative_url: "/vehicle-documents/baebb752-ac90-40aa-acd7-85ffaa94f2e7.pdf",
			vehicle_document_type_id: 81,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: 1000,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: "Another test document",
			external_url: null,
			is_active: true,
			document_type_name: "Other",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/baebb752-ac90-40aa-acd7-85ffaa94f2e7.pdf",
			is_external: false,
			display_name: "Another test document",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 4829,
			database_id: 429,
			relative_url: "/vehicle-documents/22856f8f-e67f-477c-b2f7-0c87e5eddfca.png",
			vehicle_document_type_id: 81,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: 1000,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: "logo",
			external_url: null,
			is_active: true,
			document_type_name: "Other",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/22856f8f-e67f-477c-b2f7-0c87e5eddfca.png",
			is_external: false,
			display_name: "logo",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 9380,
			database_id: 380,
			relative_url: "/vehicle-documents/0be95876-955b-4efc-b88b-211a3d954fee.png",
			vehicle_document_type_id: 81,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: null,
			organization_id: 1,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: "Image upload test",
			external_url: null,
			is_active: true,
			document_type_name: "Other",
			document_type_description: "SGC",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: true,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/0be95876-955b-4efc-b88b-211a3d954fee.png",
			is_external: false,
			display_name: "Image upload test",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		},
		{
			id: 37226,
			database_id: 376,
			relative_url: "/vehicle-documents/391798c3-f259-492a-bc9b-9c05d4a85509.jpg",
			vehicle_document_type_id: 74,
			view_count: 0,
			is_approved: true,
			inventory_item_id: null,
			vin: null,
			store_id: null,
			organization_id: null,
			year: null,
			make: null,
			model: null,
			trim: null,
			condition: null,
			customer_can_view: true,
			name: null,
			external_url: null,
			is_active: true,
			document_type_name: "Supplemental Manual",
			document_type_description: "YMM",
			default_image_filename: "document.png",
			document_sort_order: 1000,
			store_can_modify: false,
			full_url: "https://loopmein-dev.imgix.net/vehicle-documents/391798c3-f259-492a-bc9b-9c05d4a85509.jpg",
			is_external: false,
			display_name: "",
			default_image_url: "https://loopmein-dev.imgix.net/vehicle-document-types/document.png"
		}
	],
	store_settings: [
		{
			id: 529,
			name: "PRICE_SUPPLEMENTAL",
			value: '<div style="font-weight: bolder">Administration fee & Amvic: $625</div>',
			store_id: 1000,
			organization_id: null,
			children: null,
			store_setting_type: {
				setting_name: "PRICE_SUPPLEMENTAL",
				label:
					"An extra line of text below the price in a VINFO report.  HTML enabled text for whatever the dealership wants.  Mainly used in Canada to specifiy AMVIC amounts.",
				value_type: "STRING",
				is_notification_type: false,
				setting_type: "PARENT"
			}
		},
		{
			id: 577,
			name: "VEHICLE_INFO_WELCOME_VISIBLE",
			value: "lead",
			store_id: 1000,
			organization_id: null,
			children: null,
			store_setting_type: {
				setting_name: "VEHICLE_INFO_WELCOME_VISIBLE",
				label: "Settings for visiblity in the Vinfo Welcome Section",
				value_type: "STRING",
				is_notification_type: false,
				setting_type: "PARENT"
			}
		}
	],
	user_ips: "127.0.0.1",
	show_salesperson: true
};
